### ISSUE TITLE
mecab引数の誤り

### ISSUE THREAD

**Issue by Olivine-Ryo** [chakki-works/Japanese-Company-Lexicon#10]
ユーザー辞書を読み込むので引数は`-d`ではなく`-u`ではないでしょうか．

> `tagger = MeCab.Tagger('-d/usr/local/lib/mecab/dic/user_dict/jcl_slim_mecab.dic')`

**Comment by BrambleXu** [comment]
確かに`-u`の方がふさわしいですね。[wiki](https://github.com/chakki-works/Japanese-Company-Lexicon/wiki/JCLdic-Usage#1-parse-method)を更新しました。
