### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType into built in open function

### ISSUE THREAD

**Issue by ko-kamenashi** [chakki-works/Japanese-Company-Lexicon#11]
### Premise · What I want to realize

I'm trying to execute your JCLdic program, but I'm not going well...

### testing environment

- MacOS Mojave
    - 10.14.6
- Python
    - 3.8.3
- bash
    - 3.2.57

#### 1. clone This JCLdic Repository to local

```
git clone https://github.com/chakki-works/Japanese-Company-Lexicon.git
```

#### 2. prepare to execute JCLdic 

I prepared to execute this program according to README.md

1. Data Preparation

```
$ pip install -r requirements.txt
```

2. Download comnapy number data
[CSV format - Unicode](https://www.houjin-bangou.nta.go.jp/download/zenken/#csv-unicode)

3. Put the ZIP files to data/hojin/zip directory, and run below script to preprocess the data

```
$ sh scripts/download.sh
```

4. Generating alias

```
$ sh scripts/generate_alias.sh
```

5. Datasets, dictionaries, and annotated datasets preparation

```
$ python tools/dataset_converter.py
$ python tools/dataset_preprocess.py
```

6. Make sure the main.py has following setting

```
# main.py setting
entity_level = False 
# ...
### result 1 ###
# bccwj  
main(bccwj_paths, bccwj_glod, entity_level=entity_level)
# mainichi
main(mainichi_paths, mainichi_glod, entity_level=entity_level)
```
```
$ tree
.
├── Japanese-Company-Lexicon.iml
├── LICENSE
├── README.md
├── ckpts
├── data
│   ├── corpora
│   │   ├── bccwj
│   │   ├── mainichi
│   │   └── output
│   │       ├── bccwj.bio
│   │       ├── bccwj_1company.jsonl
│   │       ├── bccwj_dataset.tsv
│   │       ├── bccwj_names.csv
│   │       ├── bccwj_names_counter.json
│   │       ├── mainichi.bio
│   │       ├── mainichi_1company.jsonl
│   │       ├── mainichi_dataset.tsv
│   │       ├── mainichi_names.csv
│   │       └── mainichi_names_counter.json
│   ├── dictionaries
│   │   ├── ipadic
│   │   ├── ipadic-neologd
│   │   ├── juman
│   │   └── output
│   └── hojin
│       ├── csv
│       │   └── 13_tokyo_all_20200529.csv
│       ├── output
│       └── zip
│           └── 13_tokyo_all_20200529.zip
├── main.py
├── models
│   ├── __init__.py
│   ├── __pycache__
│   │   ├── __init__.cpython-38.pyc
│   │   ├── bilstm.cpython-38.pyc
│   │   ├── bilstm_crf.cpython-38.pyc
│   │   ├── config.cpython-38.pyc
│   │   ├── crf.cpython-38.pyc
│   │   ├── evaluate.cpython-38.pyc
│   │   ├── metrics.cpython-38.pyc
│   │   ├── tools.cpython-38.pyc
│   │   └── utils.cpython-38.pyc
│   ├── bilstm.py
│   ├── bilstm_crf.py
│   ├── config.py
│   ├── crf.py
│   ├── evaluate.py
│   ├── metrics.py
│   ├── tools.py
│   └── utils.py
├── requirements.txt
├── scripts
│   ├── download.sh
│   └── generate_alias.sh
└── tools
    ├── __pycache__
    │   ├── annotator.cpython-38.pyc
    │   └── settings.cpython-38.pyc
    ├── alias_generation.py
    ├── annotation_with_dict.py
    ├── annotator.py
    ├── coverage.py
    ├── covert_csv2jsonl.py
    ├── dataset_converter.py
    ├── dataset_preprocess.py
    ├── dictionary_preprocess.py
    ├── downloader.py
    ├── jcl_filter.py
    ├── save_mecab_format.py
    └── settings.py
```

#### 3. execute main.py from terminal

```
$ python3 main.py
```

#### roblems occurring · Error messages

```
Traceback (most recent call last):
  File "main.py", line 147, in <module>
    main(bccwj_paths, bccwj_gold, entity_level=entity_level)
  File "main.py", line 100, in main
    crf_pipeline(data_paths, gold_data_path, entity_level, low_frequency)
  File "main.py", line 41, in crf_pipeline
    counter = read_counter(low_frequency)
  File "main.py", line 14, in read_counter
    with open(path, 'r') as f:
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

#### verification

I confirmed the behavior from the code.

- **low_fequency** is Passed argument as read_counter function's argument.
- But all low_frequency value is NoneType because parent function's low_frequency defaule value into argument is None, equal NoneType.
- So, error is occured by open function into read_only function
  - open(path: str, readType: str...)
- I don't know why is low_frequency value used to open function's argument.

### that's all

Could you conferm this error? Thank you for your reading.

**Comment by BrambleXu** [comment]
Could you try it again with Python 3.6 version?

**Comment by ko-kamenashi** [comment]
I tried to execute main.py with Python v3.6 instead of v3.8.3, but same error has occured.
I think this error doesn't resolve it even if it do that. Because it cause low_frequency argument's value...doesn't it?

**Comment by BrambleXu** [comment]
It's weird. I test the `python main.py` locally and it works fine.

```
▶ python main.py     

Training and evaluating CRF model for data tagged with: bccwj
trian data: 954, test data: 410
0: f1 1.0000, precision 1.0000, recall 1.0000
1: f1 1.0000, precision 1.0000, recall 1.0000
2: f1 1.0000, precision 1.0000, recall 1.0000


Training and evaluating CRF model for data tagged with: bccwj_juman_tagged
trian data: 954, test data: 410
0: f1 0.4506, precision 0.8400, recall 0.3079
1: f1 0.7957, precision 0.9250, recall 0.6981
2: f1 0.9032, precision 0.9333, recall 0.8750
```

In the `2. prepare to execute JCLdic` that you list, between step 5 and step 6, did you run the [below command](https://github.com/chakki-works/Japanese-Company-Lexicon#datasets-dictionaries-and-annotated-datasets-preparation)?

```
# 2 Prepare dictionaries 
python tools/dictionary_preprocess.py

# 3 Annotate datasets with different dictionaries 
python tools/annotation_with_dict.py
```

Another thing is that after running the `generate_alias.sh` (`python tools/convert_csv2jsonl.py`), The `data/hojin/output/` should have a file called `company.jsonl`. But I notice that your file structure do not contain this file.

**Comment by ko-kamenashi** [comment]
I'm so sorry. It's exactly as you say, I didn't execute step 5 and step 6, and there isn't company.jsonl file.
the point you tell check and verify again. Thanks for your time.

**Comment by ko-kamenashi** [comment]
I was too late to be noticed. To gets the free dictionaries need to process step 5 and 6.

**Comment by ko-kamenashi** [comment]
@BrambleXu I think this issue resolve easyly.

https://github.com/chakki-works/Japanese-Company-Lexicon/blob/562731b793b5ba9ac564c530f27a5c7d6c7bafe3/main.py#L147
this main method call code has only 3 arguments, and 4th argument is defineted None default value.

https://github.com/chakki-works/Japanese-Company-Lexicon/blob/562731b793b5ba9ac564c530f27a5c7d6c7bafe3/main.py#L150
this main method call code has only 3 arguments, and 4th argument is defineted None default value.

So this issue occcured when the prosessing go through the open method into the read_counter method.

**Comment by BrambleXu** [comment]
I should upload the file for the 4th `counter` argument. Thanks for pointing it out. 
You could download the file from [here](https://s3-ap-northeast-1.amazonaws.com/chakki.jcl.jp/public/names_counter.zip
), uncompress it and put the files to `'data/corpora/output/`.
Then you should solve the problem.
