### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by ko-kamenashi** [chakki-works/Japanese-Company-Lexicon#12]

**Comment by ko-kamenashi** [comment]
(Probably) Typo name file is here:
Japanese-Company-Lexicon/tools/covert_csv2jsonl.py
->convert_csv2jsonl.py

Could you check it?

**Comment by BrambleXu** [comment]
Thanks, it is a typo.

**Comment by BrambleXu** [comment]
Fix https://github.com/chakki-works/Japanese-Company-Lexicon/commit/562731b793b5ba9ac564c530f27a5c7d6c7bafe3
