### ISSUE TITLE
download.sh file probably has two problems.

### ISSUE THREAD

**Issue by ko-kamenashi** [chakki-works/Japanese-Company-Lexicon#13]
### 1. downloads.sh file doesn't have a Shebang line at the beginning
https://github.com/chakki-works/Japanese-Company-Lexicon/blob/cc0ea35415138d10a01cca16cd35e0f904081ee1/scripts/download.sh#L1

I thind This file needs Shebang line for bash, doesn't it?

```
#!/bin/bash
```

The reason shebang line is  bash is because the process need to use brace expansion.

### 2. Brace expansion can't execute it by sh. ###
The README.md says 

```
sh scripts/download.sh
```

But I think Brace expansion cannot be used with sh but can be used with bash.

Could you check these if you have time?

**Comment by BrambleXu** [comment]
My OS is Mac OS with ZSH. It is no problem with the `sh scripts/download.sh`. But as you said, it is better to add Shebang line and replace the `sh` with `bash`

**Comment by BrambleXu** [comment]
Fixed https://github.com/chakki-works/Japanese-Company-Lexicon/commit/562731b793b5ba9ac564c530f27a5c7d6c7bafe3
