### ISSUE TITLE
Error in using jcl_full.dic as a user dictionary for MeCab.

### ISSUE THREAD

**Issue by TomokiMatsuno** [chakki-works/Japanese-Company-Lexicon#3]
I have tried to use jcl_full.dic as a user dictionary and got this error.

```
# command
mecab -u jcl_full.dic
# error
viterbi.cpp(50) [tokenizer_->open(param)] tokenizer.cpp(127) [d->open(dicfile[i])] dictionary.cpp(94) [(magic ^ DictionaryMagicID) == dmmap_->size()] dictionary file is broken: jcl_full.dic 
```

Here is my environment information

```
# OS
OSx 10.15.3.

# mecab version
mecab of 0.996

# dictionary information
filename:	/usr/local/lib/mecab/dic/ipadic/sys.dic
version:	102
charset:	utf8
type:	0
size:	392126
left size:	1316
right size:	1316
 ```
I can use my original user dictionary without any problem.

Is it correct to use this dictionary as a user dictionary?
And, it would be nice if you provide me with some example command or reference about how to use this dictionary.

**Comment by BrambleXu** [comment]
Thanks for the report. I am working on it.

**Comment by BrambleXu** [comment]
You can download the latest mecab dic version from README and follow the [usage](https://github.com/chakki-works/Japanese-Company-Lexicon/wiki/JCLdic-Usage).
#8
