### ISSUE TITLE
Difference between MeCab Dic 1 and MeCab Dic 2 is written nowhere in the repository.

### ISSUE THREAD

**Issue by TomokiMatsuno** [chakki-works/Japanese-Company-Lexicon#9]
I can see there are two links for MeCab dictionary for JCL_full version.

```
JCL_full (8491326, CSV, MeCab CSV, MeCab Dic 1, MeCab Dic 2): contain all kinds of names.
```

However, the difference between them is not provided.

Could you write the difference?

**Comment by BrambleXu** [comment]
The difference is the size. I update the readme. And I write the reason in [wiki](https://github.com/chakki-works/Japanese-Company-Lexicon/wiki/JCLdic-Usage#preparation)

> If you have multiple user dictionary files, you could write them in one line. I split the JCL full version into two files because MeCab cannot compile the single file due to the large file size.
